name: UConn Banner
department: University Communications
department_url: http://communications.uconn.edu/
markdown: rdiscount

exclude: [README.md, config.rb, .gitignore, sass]

# Display Site Search
search: |
        <form class="form-search">
            <input type="text" class="input-medium" placeholder="Search this site...">
            <button type="submit" class="btn">Search</button>
        </form>